name: diabetes_prediction
channels:
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - altair=5.0.1
  - arrow-cpp=19.0.0
  - asttokens=2.0.5
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - cachetools=5.5.1
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - fonttools=4.55.3
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.5.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxgboost=2.1.1
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openjpeg=2.5.2
  - openssl=3.0.15
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=2.1.1
  - pyarrow=19.0.0
  - pydeck=0.9.1
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.22.3
  - s2n=1.3.27
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - streamlit=1.41.1
  - tbb=2021.8.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - toml=0.10.2
  - toolz=1.0.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xgboost=2.1.1
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
